language: php

php:
  - '7.3'
  - '7.4'

script:
  - composer install --ignore-platform-reqs
  - composer outdated --direct
  - composer update
  - composer phpstan || true
  - composer ecs
  - composer phpmd
  - composer phpunit
